project:
  type: website

website:
  title: "Diamondback Danger Zones"
  navbar:
    title: "Diamondback Danger Zones"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true